version: '3'
services:
  web:
    container_name: schedule-container
    restart: always
    depends_on:
      - redis
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
  redis:
    container_name: redis-container
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
